openapi: 3.0.0
info:
  version: v1.0.0
  title: HackTest
  description: "This is an API for latest contest and hackathons."
servers:
  - url: "localhost:5000"
paths:
  /contests:
    get:
      summary: Returns details about a contest
      operationId: getcontests
      tags:
        - contests
      responses:
        "200":
          description:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HacTestListing"
    post:
      summary: contests
      operationId: addcontests
      tags:
        - contests
      requestBody:
        required: true
        description: contests
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contests"
      responses:
        "201":
          description: contests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/contests"
  /contests/{id}:
    get:
      summary: contests
      operationId: getcontests
      parameters:
        - name: id
          in: path
          description: The unique id.
          required: true
          schema:
            type: string
      tags:
        - contests
      responses:
        "200":
          description: contests
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
    put:
      summary: contests
      operationId: updatecontests
      parameters:
        - name: id
          in: path
          description: The unique id.
          required: true
          schema:
            type: string
      tags:
        - contests
      requestBody:
        description: contests
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contests"
      responses:
        "204":
          description: contests
    delete:
      summary: contests
      operationId: deletecontests
      parameters:
        - name: id
          in: path
          description: The unique id.
          required: true
          schema:
            type: string
      tags:
        - contests
      responses:
        "204":
          description: contests
components:
  schemas:
    HacTestListing:
      type: array
      items:
        $ref: "#/components/schemas/contests"
    contests:
      type: object
      required:
        - _id
        - name
        - url
        - start_time
        - end_time
        - duration
        - in_24_hours
        - status
      properties:
        id:
          description: Unique identifier for the restaurant
          type: string
        name:
          description: The name of the contest.
          type: string
        url:
          description: Url of the contest.
          type: string
        start_time:
          description: Starting time of the contest.
          type: string
        end_time:
          description: Ending time of the contest.
          type: string
        duration:
          description: Duration of the contest.
          type: string
        in_24_hours: Next contest in 24 hours.
          description: 
          type: string
        status:
          description: "status of of the contest."
          type: string