openapi: 3.0.0
info:
  version: v1.0.0
  title: HackTest
  description: "This is an API for latest contest and hackathons."
servers:
  - url: "http://api.example.com"
paths:
  /contests/codeforces:
    get:
      summary: contests/codeforces
      operationId: getcontests/codeforces
      tags:
        - contests/codeforces
      responses:
        "200": contests/codeforces
          description: 
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HacTestListing"
    post:
      summary: contests/codeforces
      operationId: addcontests/codeforces
      tags:
        - contests/codeforces
      requestBody:
        required: true
        description: contests/codeforces
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contests/codeforces"
      responses:
        "201":
          description: contests/codeforces
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/contests/codeforces"
  /contests/codeforces/{id}:
    get:
      summary: contests/codeforces
      operationId: getcontests/codeforces
      parameters:
        - name: id
          in: path
          description: The unique id.
          required: true
          schema:
            type: string
      tags:
        - contests/codeforces
      responses:
        "200":
          description: contests/codeforces
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Restaurant"
    put:
      summary: contests/codeforces
      operationId: updatecontests/codeforces
      parameters:
        - name: id
          in: path
          description: The unique id.
          required: true
          schema:
            type: string
      tags:
        - contests/codeforces
      requestBody:
        description: contests/codeforces
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/contests/codeforces"
      responses:
        "204":
          description: contests/codeforces
    delete:
      summary: contests/codeforces
      operationId: deletecontests/codeforces
      parameters:
        - name: id
          in: path
          description: The unique id.
          required: true
          schema:
            type: string
      tags:
        - contests/codeforces
      responses:
        "204":
          description: contests/codeforces
components:
  schemas:
    HacTestListing:
      type: array
      items:
        $ref: "#/components/schemas/contests/codeforces"
    contests/codeforces:
      type: object
      required:
        - name
        - url
        - start_time
        - end_time
        - duration
        - in_24_hours
        - status
      properties:
        id:
          description: Unique identifier for the restaurant
          type: string
        name:
          description: The name of the contest.
          type: string
        url:
          description: Url of the contest.
          type: string
        start_time:
          description: Starting time of the contest.
          type: date
        end_time:
          description: Ending time of the contest.
          type: date
        duration:
          description: Duration of the contest.
          type: number
        in_24_hours: Next contest in 24 hours.
          description: 
          type: boolean
        status:
          description: "status of of the contest."
          type: string